apiVersion: extensions/v1
kind: Deployment
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  replicas: 1
  selector:
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: hosamsaleh/udagram-reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
